### ISSUE TITLE
Leaking openai key

### ISSUE THREAD

**Issue by astolman** [UIUC-Chatbot/rlhf#1]
I'm not sure if you are aware but here https://github.com/UIUC-Chatbot/rlhf/blob/main/model/gpt3/gpt3_inference.ipynb it looks like you've left your openai key in a public document.

**Comment by KastanDay** [comment]
Thank you, I’ll make sure those keys are rotated. but this is an older repo, so I’m sure they’re gone by now. 

Anything I can help you find? I just got funding to do another round of RLHF work so I’m looking to hire MS and PhD students at the moment.

**Comment by astolman** [comment]
I was just curious how the rlhf worked, nothing in specific I was looking for.
